version: '3'

services:
  postgres:
    image: postgres:13
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:5432:5432

  hasura:
    image: hasura/graphql-engine:v1.3.2
    env_file:
      - ./.env
    network_mode: "host"

volumes:
  db:
